### ISSUE TITLE
Why not use bind?

### ISSUE THREAD

**Issue by QuentinRoy** [fundon/delegate-proxy#1]
This is a naive question: I am wondering if there is any particular reason you used a function wrapper with `apply` rather than `bind` to preserve methods' context?

Is there any particular reasons to do
```js
return 'function' === typeof value ? function method () {
    return value.apply(origin, arguments)
} : value
```
rather than the (shorter)
```js
return 'function' === typeof value ? value.bind(origin) : value
```

**Comment by QuentinRoy** [comment]
I see now this is a actually a change introduced in 78dd4a0d5a43a9d1bfa4f1c78b2524549ad13b2e.
I am surprised such a function wrapper is actually faster than `bind`.

**Comment by fundon** [comment]
Performance improvement!
